ducks.number=100

quarkus.hibernate-orm.database.generation=update

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/duckdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=sa
